### ISSUE TITLE
R2WebWiew instanciation error on Android 5

### ISSUE THREAD

**Issue by Judas** [readium/r2-navigator-kotlin#120]
Reproduction :
Launch the app on Android 5.0 or 5.1 emulator and open ebook. 
The app crash while initializing the R2WebView
This works fine on emulators with API >= 23. I don't have an Android 5 device to test to see if it is an emulator bug.

```
android.view.InflateException: Binary XML file line #28: Error inflating class org.readium.r2.navigator.R2WebView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at org.readium.r2.navigator.pager.R2EpubPageFragment.onCreateView(R2EpubPageFragment.kt:52)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at org.readium.r2.navigator.pager.R2FragmentPagerAdapter.finishUpdate(R2FragmentPagerAdapter.kt:109)
        at com.duolingo.open.rtlviewpager.DelegatingPagerAdapter.finishUpdate(DelegatingPagerAdapter.java:61)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at org.readium.r2.navigator.pager.R2RTLViewPager.onMeasure(R2RTLViewPager.java:229)
        at android.view.View.measure(View.java:17547)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:403)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
```

**Comment by vgershman** [comment]
Same issue

**Comment by mickael-menu** [comment]
The underlying exception is actually: 
```
04-14 09:40:01.041 3875-3875/org.readium.r2reader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.readium.r2reader, PID: 3875
    android.content.res.Resources$NotFoundException: String resource ID #0x2040003
        at android.content.res.Resources.getText(Resources.java:299)
        at android.content.res.Resources.getString(Resources.java:385)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
        at android.webkit.WebView.<init>(WebView.java:554)
        at android.webkit.WebView.<init>(WebView.java:489)
        at android.webkit.WebView.<init>(WebView.java:472)
        at android.webkit.WebView.<init>(WebView.java:459)
        at android.webkit.WebView.<init>(WebView.java:449)
        at org.readium.r2.navigator.R2BasicWebView.<init>(R2BasicWebView.kt:39)
        at org.readium.r2.navigator.R2WebView.<init>(R2WebView.kt:36)
```

which seems related to https://stackoverflow.com/questions/46810118/exception-on-new-webview-on-lollipop-5-1-devices

There's a workaround on the StackOverflow issue, but I'd like to see if there's not a proper way to fix this.

**Comment by mickael-menu** [comment]
Looks like [it was fixed in Appcompat 1.2.0-alpha02](https://developer.android.com/jetpack/androidx/releases/appcompat#1.2.0-alpha02).

**Comment by mickael-menu** [comment]
@Judas @vgershman  Can you check with the `fix/appcompat` branches in `r2-opds-kotlin`, `r2-shared-kotlin`, `r2-streamer-kotlin`, `r2-navigator–kotlin` and `r2-testapp-kotlin`? You will also need to upgrade Appcompat in your app:

```
implementation "androidx.appcompat:appcompat:1.2.0-beta01"
```

Although there might be other issues with these older devices, it looks like the user settings are not applied:

<img width="500" alt="Screenshot 2020-04-14 at 10 15 11" src="https://user-images.githubusercontent.com/58686775/79202847-7dae4f80-7e3a-11ea-8d3d-f8e45c4ccaf9.png">

**Comment by Judas** [comment]
I confirm the fix in the branches.
Upgrading appcompat in the integration app also fixed the crash without needing a readium update, with the same drawbacks.

**Comment by vgershman** [comment]
I got an alternative solution

`android:configChanges="uiMode"` in AndroidManifest

**Comment by HadrienGardeur** [comment]
I think it would be worth having @JayPanoz input on this matter as well. If I remember correctly, we've had discussions before about targeting strictly 6.0+ for various CSS related matters.

**Comment by JayPanoz** [comment]
As far as I can remember, we decided to make it Android 5+, as 4.4.4 and it's old/legacy webview was the main issue for CSS custom properties (IE11 support was abandoned for the same reason).

**Comment by mickael-menu** [comment]
@vgershman 
> I got an alternative solution
> 
> `android:configChanges="uiMode"` in AndroidManifest

Does this by any chance fix the user settings issue in the screenshot I posted above?

**Comment by vgershman** [comment]
@mickael-menu No, it isn't. Same result as using -beta appcompat.

**Comment by mickael-menu** [comment]
@vgershman 

Too bad, then I suggest that you upgrade Appcompat if you can instead of changing `configChanges`:

> Note: Using this attribute should be avoided and used only as a last resort. Please read Handling Runtime Changes for more information about how to properly handle a restart due to a configuration change.
> https://developer.android.com/guide/topics/manifest/activity-element
